cabinet/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from cabinet import views

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='cabinet-index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='cabinet-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='cabinet-logout'),
    path('request/list/', login_required(views.RequestList.as_view()), name='cabinet-request-list'),
    path('group/list/', login_required(views.GroupList.as_view()), name='cabinet-group-list'),
    path('group/create/', login_required(views.GroupCreate.as_view()), name='cabinet-group-create'),
]

champion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabinet/', include('cabinet.urls')),
    path('', include('promo.urls')),
]

promo/urls.py
from django.urls import path

from promo import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='promo-index'),
]

cabinet/models.py
from django.db import models
from django.contrib.auth.models import User


class Place(models.Model):
    name = models.CharField(max_length=255, unique=True)
    key = models.CharField(max_length=32, unique=True)


class Trainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Group(models.Model):
    COURSE_SDG = 'sdg' # Sports development group - группа спортивного совершенствования
    COURSE_TG = 'tg' # Training group - учебно-тренировочная группа
    COURSE_ITG1 = 'itg1' # 1st year initial training group - группа начальной подготовки 1-ого года
    COURSE_ITG2 = 'itg2' # Initial training group 2nd year - группа начальной подготовки 2-ого года
    COURSE_WG = 'wg' # Weekend group - группа выходного дня
    COURSE_CHOICES = (
        (COURSE_SDG, 'ГСС'),
        (COURSE_TG, 'УТГ'),
        (COURSE_ITG1, 'ГНП-1'),
        (COURSE_ITG2, 'ГНП-2'),
        (COURSE_WG, 'ГВД'),
    )

    course = models.CharField(choices=COURSE_CHOICES, max_length=16)


class Schedule(models.Model):
    DAY_MONDAY = 1
    DAY_TUESDAY = 2
    DAY_WEDNESDAY = 3
    DAY_THURSDAY = 4
    DAY_FRIDAY = 5
    DAY_SATURDAY = 6
    DAY_SUNDAY = 7
    DAY_CHOICES = (
        (DAY_MONDAY, 'Понедельник'),
        (DAY_TUESDAY, 'Вторник'),
        (DAY_WEDNESDAY, 'Среда'),
        (DAY_THURSDAY, 'Четверг'),
        (DAY_FRIDAY, 'Пятница'),
        (DAY_SATURDAY, 'Суббота'),
        (DAY_SUNDAY, 'Воскресение'),
    )

    week_day = models.PositiveSmallIntegerField(choices=DAY_CHOICES)
    start_time = models.TimeField()
    end_time = models.TimeField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    trainers = models.ManyToManyField(User)

promo/models.py
from django.db import models


class RequestInfo(models.Model):
    children_name = models.CharField(max_length=255)
    children_birthday = models.DateField()
    phone = models.CharField(max_length=32)
    email = models.EmailField()
    name = models.CharField(max_length=255)
    comments = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(null=True, auto_now_add=True)

cabinet/forms.py
from django import forms

from cabinet.models import Group


class GroupForm(forms.Form):
    course = forms.ChoiceField(choices=Group.COURSE_CHOICES, label='Направление')

promo/forms.py
from django import forms

from promo.models import RequestInfo


class RequestForm(forms.ModelForm):
    agreement = forms.BooleanField()

    class Meta:
        model = RequestInfo
        fields = ('children_name', 'children_birthday', 'phone', 'email',
                  'name', 'comments', 'agreement')

cabinet/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView

from cabinet.forms import GroupForm
from cabinet.models import Group, Schedule
from promo.models import RequestInfo


class IndexView(TemplateView):
    template_name = 'cabinet.html'


class RequestList(ListView):
    model = RequestInfo
    template_name = 'request-list.html'
    paginate_by = 3

    def get_ordering(self):
        if self.request.GET.get('id') == 'desc':
            return '-id'
        if self.request.GET.get('id') == 'asc':
            return 'id'

        return '-id'


class GroupList(ListView):
    model = Group
    template_name = 'group-list.html'


class GroupCreate(FormView):
    template_name = 'group-create.html'
    form_class = GroupForm
    success_url = reverse_lazy('cabinet-group-list')

    def get_context_data(self, *args, **kwargs):
        context = super(GroupCreate, self).get_context_data(*args, **kwargs)
        context['week_days'] = Schedule.DAY_CHOICES
        return context

    def form_valid(self, form):
        Group.objects.create(course=form.cleaned_data['course'])
        return super(GroupCreate, self).form_valid(form)

promo/views.py
from django.views.generic.edit import CreateView
from django.urls import reverse

from promo.forms import RequestForm


class IndexView(CreateView):
    template_name = 'promo.html'
    form_class = RequestForm

    def get_success_url(self, **kwargs):
        return reverse('promo-index') + '?success=1'

cabinet/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS, then Slick.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

cabinet/templates/cabinet.html
{% extends "base.html" %}
{% load static %}

{% block content %}Hello, world!{% endblock %}

cabinet/templates/group-create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <form method="post" role="form" action="{% url 'cabinet-group-create' %}">
        {% if form.non_field_errors %}
        <div class="form-group">
            {% for error in form.non_field_errors %}
            <p class="help-block text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="course">Направление</label>
            <select id="{{ form.course.auto_id }}" class="form-control" name="{{ form.course.name }}">
                {% for value, text in form.course.field.choices %}
                <option value="{{ value }}" {% if value|slugify == field.value|slugify %}selected{% endif %}>
                    {{ text }}
                </option>
                {% endfor %}
            </select>
            {% for error in form.course.errors %}
            <span class="help-block text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="control-label">Расписание</label>
            {% for error in form.schedule.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
            <input type="hidden" name="schedule">
            <button type="button" class="btn btn-link" title="Добавить" data-toggle="modal"
                data-target="#schedule-modal">
                <span class="fa fa-plus-circle"></span>
            </button>
            <table id="schedule-table" class="table table-striped">
                <thead>
                    <th>День недели</th>
                    <th>Время начала</th>
                    <th>Время окончания</th>
                    <th>Место</th>
                    <th>Тренер</th>
                    <th></th>
                </thead>
                <tbody>
                    <tr></tr>
                </tbody>
            </table>
        </div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
    <div class="modal fade" id="schedule-modal" tabindex="-1" role="dialog" aria-labelledby="schedule-modal-label"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="schedule-modal-label">Расписание</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="week-day" class="control-label">День недели</label>
                            <select class="form-control" name="week-day">
                                {% for key, name in week_days %}
                                <option value="{{ key }}">{{ name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-primary" id="schedule-create-button">Добавить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js-libs %}
<script>
    var schedules = [];
    var lastScheduleId = 0;

    function scheduleIndexOf(id) {
        for (var i = 0; i < schedules.length; i++) {
            if (schedules[i]["scheduleId"] === id) {
                return i;
            }
        }
        return -1;
    }

    function syncSchedule() {
        var schedule = ''
        for (var i = 0; i < schedules.length; i++) {
            if (i > 0) {
                schedule += ','
            }
            schedule += schedules[i].weekDayId
        }
        $('input[name=schedule]').val(schedule);
    }

    $('#schedule-create-button').on('click', function (event) {
        var id = lastScheduleId++

        var weekDay = $('select[name=week-day] option:selected')
        $('#schedule-table').append(
            '<tr id="schedule-row-' + id + '">' +
            '<td data-week-day="' + weekDay.val() + '">' + weekDay.text() + '</td>' +
            '<td></td>' +
            '<td></td>' +
            '<td></td>' +
            '<td></td>' +
            '<td><a id="remove-schedule-' + id + '"><span class="fa fa-trash"></span></a></td>' +
            '</tr>'
        )

        schedules.push({
            scheduleId: id,
            weekDayId: weekDay.val(),
        });
        syncSchedule();

        $('#remove-schedule-' + id).on('click', function (event) {
            $('#schedule-row-' + id).remove();
            schedules.splice(scheduleIndexOf(id), 1)
            syncSchedule();
        })

        $('#schedule-modal').modal('hide')
    })
</script>
{% endblock %}

cabinet/templates/group-list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div>
    <a role="button" class="btn btn-primary btn-sm " href="{% url 'cabinet-group-create' %}">Создать</a>
    <table>
      <thead>
        <th>ID</th>
        <th>Направление</th>
      </thead>
      <tbody>
        {% for g in object_list %}
        <tr>
          <th>{{ g.id }}</th>
          <td>{{ g.course }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>    
  </div>
{% endblock %}

cabinet/templates/group_confirm_delete.html
<form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
    

cabinet/templates/group_create.html
{% extends "base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать">
    </form>
{% endblock %}

cabinet/templates/group_detail.html
{% extends "base.html" %}
{% load compact_fullname %}

{% block content %}
    <p>Направление: {{ object.course.name }}</p>
    <div class="container">

        <h1>Расписание</h1>
        <table class="table">
            <thead>
                <th>День недели</th>
                <th>Время начала</th>
                <th>Продолжнительность</th>
                <th>Место</th>
                <th>Тренеры</th>
                <th></th>
            </thead>
            <tbody>
                {% for l in lessons %}
                <tr>
                    <td>{{ l.get_week_day_display }}</td>
                    <td>{{ l.start_time }}</td>
                    <td>{{ l.duration }}</td>
                    <td>{{ l.place.name }}</td>
                    <td>
                        {% for t in l.trainer.all %}
                        {% if not forloop.first %}, {% endif %}
                        {{ t|compact_fullname}}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'lesson-delete' l.group_id l.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a role="button" class="btn btn-primary btn-sm " href="{% url 'lesson-create' object.id %}">Добавить</a>
    </div>
{% endblock %}

cabinet/templates/group_list.html
{% extends "base.html" %}

{% block content %}
    <a role="button" class="btn btn-primary btn-sm " href="{% url 'group-create' %}">Добавить</a>
    <div class="group-list">
        <table class="table table-striped">
            <thead>
                <th>Направление</th>
                <th>Расписание</th>
                <th></th>
            </thead>
            <tbody>
                {% for group in object_list %}
                <tr>
                    <td>{{ group.course.name }}</td>    
                    <td>

                    </td>
                    <td>
                        <a role="button" class="btn btn-primary btn-sm " href="{% url 'group-detail' group.id %}">Редактировать</a>
                        <a role="button" class="btn btn-danger btn-sm " href="{% url 'group-delete' group.id %}">Удалить</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

cabinet/templates/lesson_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

cabinet/templates/lesson_create.html
{% extends "base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать">
    </form>
{% endblock %}

cabinet/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <form class="form-signin" method="post" action="{% url 'cabinet-login' %}">
      <h2 class="form-signin-heading">Please sign in</h2>

      <div class="form-group has-error">
        {% for error in form.non_field_errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>

      {% csrf_token %}
      <div class="form-group {% if form.username.errors %}has-error{% endif %}">
          <label for="{{ form.username.auto_id }}" class="control-label">
            {{ form.username.label }}
          </label>

          <input type="text" id="{{ form.username.auto_id }}" class="form-control" name="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}">

          {% if form.username.help_text %}
          <span class="help-block">{{ form.username.help_text }}</span>
          {% endif %}

          {% for error in form.username.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
      </div>
      <div class="form-group {% if form.password.errors %}has-error{% endif %}">
          <label for="{{ form.password.auto_id }}" class="control-label">
            {{ form.password.label }}
          </label>

          <input type="password" id="{{ form.password.auto_id }}" class="form-control" name="{{ form.password.name }}" value="{{ form.password.value|default_if_none:'' }}">

          {% if form.password.help_text %}
          <span class="help-block">{{ form.password.help_text }}</span>
          {% endif %}

          {% for error in form.password.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
      </div>
      <input type="hidden" name="next" value="{{ next }}" />
      <input class="btn btn-primary btn-block form-signin-submit" type="submit" value="sigin" />
    </form>
  </div>
{% endblock %}

cabinet/templates/logout.html
{% extends "base.html" %}

{% block content %}
  <div class="container text-center">
    Logged out!
  </div>
{% endblock %}

cabinet/templates/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
            <a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Previous">
            <a href="#">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}

        {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
            <a href="?page={{ page }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li>
            <a href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Next">
            <a href="#">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

cabinet/templates/request-list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  {% include "pagination.html" %}
  <div>
    <table class="table">
      <thead>
        <tr>
          <th>
            ID
            {% if request.GET.id == "desc" %}
            <a href="{% url 'cabinet-request-list' %}?id=asc">
              <span class="fa fa-sort-down"></span>
            </a>
            {% elif request.GET.id == "asc" %}
            <a href="{% url 'cabinet-request-list' %}?id=desc">
                <span class="fa fa-sort-up"></span>
            </a>
            {% else %}
            <a href="{% url 'cabinet-request-list' %}?id=desc">
              <span class="fa fa-sort"></span>
            </a>
            {% endif %}
          </th>
          <th>Время создания заявки</th>
          <th>ФИО</th>
          <th>Дата рождения</th>
          <th>Номер телефона</th>
          <th>Email</th>
          <th>Пожелания</th>
        </tr>
      </thead>
      <tbody>
        {% for r in object_list %}
        <tr>
          <th>{{ r.id }}  </th>
          <td>{{ r.created_at }}</td>
          <td>{{ r.children_name }}</td>
          <td>{{ r.children_birthday }}</td>
          <td>{{ r.phone }}</td>
          <td>{{ r.email }}</td>
          <td>{{ r.comments }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

champion/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>СК «Чемпион»</title>
    <!-- TODO: favicon -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block css-libs %}{% endblock %}

    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static '/main.css' %}">
    
    <script type="text/javascript" >
       (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
       m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
       (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

       ym(54156424, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
       });
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img class="d-inline-block align-top logo-img" src="{% static '/images/brand.png' %}" alt="">
        </a>
        <div class="justify-content-end">
          <div class="navbar-info">
            <p>
              <a href="mailto:info@swimchampion.ru">
                <span class="fa fa-envelope"></span>info@swimchampion.ru
              </a>
              <a href="tel:+7(499)938-59-68">+7(499)938-59-68</span>
                <a class="fa fa-facebook" href="https://www.facebook.com/swimchampion2011"></a>
                <a class="fa fa-instagram" href="https://www.instagram.com/sportclubchampion/"></a>
                <a class="fa fa-vk" href="https://vk.com/swimchampion"></a>
            </p>
            <p>
              Адрес: г.Москва, ул. Корнейчука, д.28, к.2
            </p>
          </div>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <footer class="block-wrapper bg-light">
      <ul class="nav justify-content-center nav-info">
        <li class="nav-item">
          <a href="mailto:info@swimchampion.ru">
            <span class="fa fa-envelope"></span>info@swimchampion.ru
          </a>
        </li>
        <li class="nav-item">
          <a href="tel:+7(499)938-59-68">+7(499)938-59-68</span>
        </li>
        <li class="nav-item">
          <a class="fa fa-facebook" href="https://www.facebook.com/swimchampion2011"></a>
        </li>
        <li class="nav-item">
          <a class="fa fa-instagram" href="https://www.instagram.com/sportclubchampion/"></a>
        </li>
        <li class="nav-item">
          <a class="fa fa-vk" href="https://vk.com/swimchampion"></a>
        </li>
      </ul>
    </footer>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>

    {% block js-libs %}{% endblock %}
    <noscript><div><img src="https://mc.yandex.ru/watch/54156424" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  </body>
</html>

promo/templates/request_info.html
{% load static %}
<form method="POST" action="{% url 'promo-index' %}">
  {% if form.non_field_errors %}
  <div class="form-group">
      {% for error in form.non_field_errors %}
      <p class="help-block text-danger">{{ error }}</p>
      {% endfor %}
  </div>
  {% endif %}
  {% csrf_token %}
  <div class="form-group">
    <label for="children_name">Фамилия и имя ребенка</label>
    <input class="form-control" type="text" name="children_name" value="{{ form.children_name.value|default_if_none:'' }}" required>
    {% for error in form.children_name.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <div class="form-group">
    <label for="children_birthday">Дата рождения</label>
    <input class="form-control" type="date" name="children_birthday" value="{{ form.children_birthday.value|default_if_none:'' }}" required>
    {% for error in form.children_birthday.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <div class="form-group">
    <label for="phone">Контактный телефон родителя</label>
    <input class="form-control" type="tel" name="phone" value="{{ form.phone.value|default_if_none:'' }}" required>
    {% for error in form.phone.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <div class="form-group">
    <label for="email">Электронная почта родителя</label>
    <input class="form-control" type="email" name="email" value="{{ form.email.value|default_if_none:'' }}" required>
    {% for error in form.email.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <div class="form-group">
    <label for="name">Как к вам обращаться</label>
    <input class="form-control" type="text" name="name" value="{{ form.name.value|default_if_none:'' }}" required>
    {% for error in form.name.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <!-- TODO: Выберите удобное время для посещения -->
  <!-- TODO: Выберите уровень подготовленности Вашего ребенка (не умеет плавать / умеет держаться на воде / хорошо плавает) -->
  <div class="form-group">
    <label for="comments">Комментарий</label>
    <input class="form-control" type="text" name="comments" value="{{ form.comments.value|default_if_none:'' }}" >
    {% for error in form.comments.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <div class="form-check">
    <label class="form-check-label" for="agreement">
      <input class="form-check-input" type="checkbox" name="agreement" {% if form.agreement.value %}checked{% endif %} required>
      Я даю <a href="{% static '/docs/agreement.pdf' %}">согласие на обработку персональных данных</a>
    </label>
    {% for error in form.agreement.errors %}
      <span class="help-block text-danger">{{ error }}</span>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary">Оформить заявку</button>
</form>